const entiremenu = [
  {
    "soups & starters": {
      P1: {
        id: 1,
        name: "Ostrokyslá polievka",
        img: "./images/P1",
        price: 150,
        weight: "200ml",
        ingredients: [
          "kuracie mäso",
          "mrkva",
          "hríby",
          "bambus",
          "paprika",
          "vajíčko",
        ],
        allergens: [3, 6],
      },
      P2: {
        id: 2,
        name: "Jarné závitky zeleninové",
        img: "./images/P2.avif",
        price: 200,
        weight: "5ks",
        ingredients: ["zelenina", "múka"],
        allergens: [1, 6],
      },
    },
  },
  {
    "main dish": {
      HJ1: {
        id: 1,
        name: "Kuracie mäso Kung-pao",
        img: "./images/HJ1.avif",
        price: 480,
        weight: "120g",
        ingredients: [
          "kuracie mäso",
          "paprika",
          "mrkva",
          "hríby",
          "kapusta",
          "cibuľa",
        ],
        allergens: [6],
      },
      HJ2: {
        id: 2,
        name: "Kuracie mäso Chop suey",
        img: "./images/HJ2.avif",
        price: 480,
        weight: "120g",
        ingredients: [
          "kuracie mäso",
          "mrkva",
          "bambus",
          "hríby",
          "kapusta",
          "cibuľa",
          "pór",
        ],
        allergens: [6],
      },
      HJ3: {
        id: 3,
        name: "Osem drahocennosti",
        img: "./HJ3.avif",
        price: 520,
        weight: "120g",
        ingredients: [
          "kuracie",
          "bravčové mäso",
          "hovädzie mäso",
          "paprika",
          "mrkva",
          "hríby",
          "kapusta",
          "cibuľa",
        ],
        allergens: [6],
      },
      HJ4: {
        id: 4,
        name: "Chrumkavá kačica",
        img: "./HJ4.avif",
        price: 600,
        weight: "150g",
        ingredients: ["kačacie mäso", "jemne ostrá omáčka"],
        allergens: [1, 3, 6],
      },
      HJ5: {
        id: 5,
        name: "Bravčové chop suey",
        img: "./HJ5.avif",
        price: 500,
        weight: "150g",
        ingredients: ["bravčové mäso", "mrkva", "kapusta", "cibuľa"],
        allergens: [6],
      },
    },
  },
  {
    sides: {
      R1: {
        id: 1,
        name: "Pražená ryža s vajíčkom",
        img: "./R1.avif",
        price: 200,
        weight: "200g",
        ingredients: ["ryža", "hrášok", "mrkva", "kukurica", "vajíčko"],
        allergens: [1, 6],
      },
      R2: {
        id: 2,
        name: "Pražené špagetové rezance so zeleninou",
        img: "./R2.avif",
        price: 300,
        weight: "200g",
        ingredients: ["špagety", "mrkva", "pór", "kapusta", "vajíčko"],
        allergens: [1, 3, 6],
      },
      R3: {
        id: 3,
        name: "Pražené špagetové rezance s kuracím mäsom",
        img: "./R3.avif",
        price: 460,
        weight: "200g",
        ingredients: [
          "špagety",
          "mrkva",
          "pór",
          "kapusta",
          "vajíčko",
          "kuracie mäso",
        ],
        allergens: [1, 3, 6],
      },
      R4: {
        id: 4,
        name: "Pražené ryžové rezance s kuracím mäsom",
        img: "./R4.avif",
        price: 540,
        weight: "200g",
        ingredients: [
          "ryžové rezance",
          "mrkva",
          "pór",
          "kapusta",
          "vajíčko",
          "kuracie mäso",
        ],
        allergens: [3, 6],
      },
      R5: {
        id: 5,
        name: "Hranolky",
        img: "./R5.avif",
        price: 200,
        weight: "150g",
      },
    },
  },
  {
    salads: {
      SA1: {
        id: 1,
        name: "Nepikantný kapustový šalát",
        img: "./SA1.avif",
        price: 200,
      },
      SA2: {
        id: 2,
        name: "Pikantný kapustový šalát",
        img: "./SA1.avif",
        price: 200,
      },
    },
  },
  {
    desserts: {
      D1: {
        id: 1,
        name: "Vyprážaný banán v mede",
        img: "./D1.avif",
        price: 290,
        weight: "6ks",
        allergens: [1, 3],
      },
    },
  },
  {
    drinks: {
      N1: {
        id: 1,
        name: "Coca Cola Zero",
        img: "./N1.avif",
        price: 185,
        weight: "0.5l",
      },
      N2: {
        id: 2,
        name: "Coca Cola",
        price: 185,
        weight: "0.5l",
      },
      N3: {
        id: 3,
        name: "Sprite",
        price: 185,
        weight: "0.5l",
      },
      N4: {
        id: 4,
        name: "Fuze tea peach",
        img: "./N4.avif",
        price: 205,
        weight: "0.5l",
      },
      N5: {
        id: 5,
        name: "Fuze tea green",
        img: "./N5.avif",
        price: 205,
        weight: "0.5l",
      },
    },
  },
];
